![1763983866991](image/test/1763983866991.png)
![1763983973011](image/test/1763983973011.png)
![1763984044448](image/test/1763984044448.png)
![1763984117126](image/test/1763984117126.png)

In [2]:
# 数据操作
import torch

In [3]:
# 张量表示一个数值组成的数组，这个数组可能有多个维度
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 通过张量的shape属性来访问张量的姓皇族那个和张量重元素的总数
# 输出的是一个 torch.Size 对象。
x.shape

torch.Size([12])

In [5]:
# 输返回张量中元素的总数，永远是一个标量
x.numel()

12

In [6]:
# 改变一个张量的形状而不改变元素数量和元素值
# reshape的形状所能容纳的数据数量必须和原数据的数量相等
x = x.reshape(3,4)
x


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
# 创建全0元素
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# 创建全1元素
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
# 创建张量
torch.tensor(
    [
        [2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1],
    ]
)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
#  带小数点自动识别为浮点数
x = torch.tensor(
    [1.0, 2, 4, 8],
)
y = torch.tensor(
    [2, 2, 2, 2],
)
# 可以进行相关运算，每个子元素进行计算
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
# exp(x)=(ex1​,ex2​,...,exn​)
# 对一个张量的每一元素计算e的x次方
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
# 把多个张量结合再一起
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))

Y = torch.tensor(
    [
        [2.0, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1],
    ]
)
# 合并两个张量
torch.cat(
    (X, Y),
    dim=0,  # 在第0维合并
),

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),)

In [16]:
torch.cat(
    (X, Y),
    dim=1,  # 在第一维合并
)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [18]:
# 使用逻辑运算符构建二维张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# 对张量中的所有元素进行求和会产生一个只有一个元素的张量
X.sum()
# 一定注意生成的是一个张量

tensor(66.)

In [22]:
# 即使形状不同，我们仍然可以通过 广播机制来执行元素操作
# 注意！ 广播机制可以发生在 形状不同的张量之间，
# 但是无法发生在维度不同的张量之间
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
# 底层运算操作时
# 会把同一纬度下的 小数向大数靠拢
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [30]:
# 元素可以切片访问
X,X[-1], X[0:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [31]:
# 对单个元素进行赋值
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 对多个元素进行统一赋值
# 按区域赋值
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 运行一些操作可能会导致为新结果分配内存
before = id(Y)
Y = Y + X  # 因为发生了重复使用，原内存已经被析构，导致内存重新分配
id(Y) == before

False

In [36]:
# 执行原地操作
z = torch.zeros_like(Y)
print("id(Z):", id(z))
z[:] = X + Y
print("id(Z):", id(z))

id(Z): 1672081110320
id(Z): 1672081110320


In [ ]:
# 如果在后续计算中没有重复使用X，我们也可以使用